services:
  qbittorrent-matrix:
    build:
      context: https://github.com/ricardo-duarte-av/qbittorrent-matrix.git
    image: qbittorrent-matrix
    container_name: qbittorrent-matrix
    restart: unless-stopped
volumes:
      - ./config.yaml:/app/config.yaml:ro
